### ISSUE TITLE
Improve accessibility for play button

### ISSUE THREAD

**Issue by knarkzel** [sharu725/youtube-embed#20]
The play button should have an accessible name, see screenshot below.

![Buttons do not have an accesible name](https://github.com/sharu725/youtube-embed/assets/85593302/15779401-54af-45d4-90b5-a15738f922d9)

**Comment by knarkzel** [comment]
See https://github.com/sharu725/youtube-embed/pull/21

**Comment by sharu725** [comment]
#21 solved this
