### ISSUE TITLE
Use the no-cookies URL instead

### ISSUE THREAD

**Issue by FWORDIE** [sharu725/youtube-embed#26]
Thanks for this great snippet, was just wondering if there is any reason why it doesn't use the 'https://www.youtube-nocookie.com/embed' path, as this is much better for privacy and performance (I am told).

Thanks

**Comment by sharu725** [comment]
It is not useful for this plugin because we are showing an image initially and only when clicked on play, we embed the video. 
Enhanced Privacy Embed tells us that no cookies are set unless the user starts playing the video. This is already the case when using this plugin.

**Comment by FWORDIE** [comment]
good to know, thanks
